ARG DOCKER_BASE_IMG_REPO
ARG DOCKER_BASE_IMG_TAG
FROM $DOCKER_BASE_IMG_REPO:$DOCKER_BASE_IMG_TAG

# Set maintainer label
LABEL MAINTAINER=contact@romainlabat.fr

# Set Docker and GCloud arguments
ARG DEBIAN_FRONTEND=noninteractive

# Install Docker if DOCKER_ENABLED is true
RUN curl -sSL https://get.docker.com | bash && rm -rf /var/lib/apt/lists/*